### ISSUE TITLE
Google chrome icon

### ISSUE THREAD

**Issue by ghost** [Madkita/Plasma-Themes#3]
Hello, can you also make a google chrome icon?

**Comment by Blacksuan19** [comment]
Sorry no, I don't have any experience with icon packs 
And this is not an icon pack 
And I don't use chrome

**Comment by ghost** [comment]
Oh okay, I thought the icons in the systray are part of the theme.

**Comment by Blacksuan19** [comment]
oh, yeah those are part of the theme 
but as far as I know, chrome icon wouldn't be theme-able
