### ISSUE TITLE
Un-themed panel icons 

### ISSUE THREAD

**Issue by gdfox** [Madkita/Plasma-Themes#4]
Hi,

I have installed the Aes Nomad theme, however not all the panel icons are showing. They are showing the Breeze icons.
I cleared my cache, and reinstalled the theme many times, but it doesn't change anything. 

Please advise.

Thanks,
Greg

**Comment by Blacksuan19** [comment]
Can you post a screenshot of the current panel situation?

**Comment by gdfox** [comment]
![selection_019](https://user-images.githubusercontent.com/341095/38168303-4f08a2bc-3516-11e8-988d-d5a13a22488c.png)

**Comment by Blacksuan19** [comment]
I haven't themed some icons in the first place so the system will just show the default ones 

Nothing is wrong here
